# file: backend/agents/report_writer.py
import os
from typing import Dict, Any
from backend.utils.logger import setup_logger
from backend.utils.config import get_llm_with_fallback, invoke_with_fallback
from langchain_core.messages import SystemMessage, HumanMessage
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader

logger = setup_logger(__name__)

class ReportWriterAgent:
    def __init__(self, output_dir: str = "backend/report"):
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)
        self.llm = get_llm_with_fallback(provider="groq", model_index=0)

    async def generate_executive_summary(self, analysis_results: Dict[str, Any]) -> str:
        """Generate a text summary of the entire analysis."""
        # Extract key insights from various agents
        stats = analysis_results.get("statistical_analysis", {})
        quality = analysis_results.get("data_quality", {})
        
        prompt = f"""
        Write an Executive Summary for a Business Intelligence Report.
        
        Data Quality Score: {quality.get('quality_score', 'N/A')}
        Key Correlations: {stats.get('correlations', {}).get('strong_correlations', [])}
        
        The summary should be professional, concise, and highlight the most important findings.
        """
        
        messages = [
            SystemMessage(content="You are a Report Writer."),
            HumanMessage(content=prompt)
        ]
        
        try:
            response = await invoke_with_fallback(self.llm, messages, provider="groq")
            return response.content
        except Exception as e:
            logger.error(f"Summary generation failed: {e}")
            return "Executive summary could not be generated."

    def create_pdf_report(self, task_id: str, analysis_results: Dict[str, Any], summary: str) -> str:
        """Generate a PDF report using ReportLab."""
        filename = f"{task_id}_report.pdf"
        filepath = os.path.join(self.output_dir, filename)
        
        c = canvas.Canvas(filepath, pagesize=letter)
        width, height = letter
        
        # Title Page
        c.setFont("Helvetica-Bold", 24)
        c.drawString(100, height - 100, "AI Business Intelligence Report")
        c.setFont("Helvetica", 12)
        c.drawString(100, height - 130, f"Task ID: {task_id}")
        c.drawString(100, height - 150, "Generated by AI Copilot")
        
        c.showPage()
        
        # Executive Summary
        c.setFont("Helvetica-Bold", 18)
        c.drawString(50, height - 50, "Executive Summary")
        
        text = c.beginText(50, height - 80)
        text.setFont("Helvetica", 12)
        # Simple text wrapping (very basic)
        words = summary.split()
        line = ""
        for word in words:
            if c.stringWidth(line + " " + word) < 500:
                line += " " + word
            else:
                text.textLine(line)
                line = word
        text.textLine(line)
        c.drawText(text)
        
        c.showPage()
        
        # Visualizations
        c.setFont("Helvetica-Bold", 18)
        c.drawString(50, height - 50, "Visualizations")
        
        y_pos = height - 100
        charts = analysis_results.get("visualizations", {})
        
        # Flatten chart list
        all_charts = []
        for category in charts:
            all_charts.extend(charts[category])
            
        for chart_path in all_charts[:5]: # Limit to 5 charts for now
            if os.path.exists(chart_path):
                try:
                    # Draw image
                    c.drawImage(chart_path, 50, y_pos - 300, width=500, height=300)
                    y_pos -= 320
                    if y_pos < 50:
                        c.showPage()
                        y_pos = height - 50
                except Exception as e:
                    logger.error(f"Failed to add image {chart_path}: {e}")
                    
        c.save()
        logger.info(f"PDF Report generated: {filepath}")
        return filepath

    async def generate_report(self, task_id: str, analysis_results: Dict[str, Any]) -> Dict[str, str]:
        """Main entry point."""
        summary = await self.generate_executive_summary(analysis_results)
        pdf_path = self.create_pdf_report(task_id, analysis_results, summary)
        
        return {
            "summary": summary,
            "pdf_path": pdf_path
        }
# end file
